import Effect from '@/components/effect'
import Header from '@/components/Header'
import Theme from '@/components/Theme'
import WrapperRedux from '@/components/WrapperRedux'
import './globals.css'

export const metadata = {
  title: 'Aidin Rezaei',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <WrapperRedux>
          <Effect />
          <Theme>
            <Header />
            {children}
          </Theme>
        </WrapperRedux>
      </body>
    </html>
  )
}
